services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - APP_ENV=production
      - DATABASE_URL=
      - PROJECT_NAME=Tweeza
      - API_STR=/api
      - SECRET_KEY=tweeza_secret_key_replace_this_in_production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=10080
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://127.0.0.1:3000"]

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload